#!/bin/bash


#create User with args

echo "-------------------------creating Üser ----------------------------"

#read -p "Enter username: " $1
#read -p "Enter password: " $2

sudo useradd -M $1
echo -e "$2\n$2" | sudo passwd $1

echo "--------------------------Üser added successfully -----------------------------"


sudo cat /etc/passwd | grep $1

